language: cpp

env:
  global:
   - secure: bb4rPjeG7RmX5vuxnRNvG4xPTw0RYTQm32WxexYpSysuxiomRLdBbdqnj6LfzuxDu7US6+n2eZw9XN8OZKxN9b/iZWwDgwTKPt42oIttjbleYCa438XnQdsPDYFlMNoDr/HuWrYI8jfmItPlQobHYxD6e8ZkeRtbvEb4MiUZseqPYyX6SgYgxssWUaJJOOXWxaCu0Q2ORmCTT4xVs95Cj03nxOeKKEwNfS4qoy44Fabsiha1hDoNVUEpv19Xv68EJ+4CHYLlGkH3vUE88b+Er5+YCTkyY3fYSZCZvty8YETKrhjPSr1XcHmAR9Frly3i/INEekztXhuLAaV/qr0L2JXZizN3Vo3myvzDUWhgN30pPTbjIu7i01uTmqW9/kydOFDzRosixx+YihTG7WAezHwEoSjMAEfI075uET1B/MczZcz7qNPzGojr0esVvd26HiBp9NEdvtqsAW8dOCRKGRWgzQDEy6mxmTORvFtCRV7Ip9bWOIIVqxlIxv9JPCu2XdXk2pp7dh4OzbhAv0FL8FI/J49/f7LAbt30zQSUzXUgHWMCdm97F4roRuQc8sak/uZLYz+pX0r6oetOdR+lvVQ1z2mQH1cIS2HYZn6fmkATKYeULRr6x8y0+aarcsuCS3j75cJ5x3yHqfCWsZoFafEF/A+4rIY+0VwPyHmbJDk=
   - FORCE_INSTALL=1

matrix:
  include:
  - os: osx
    compiler: clang

    script:
    - "./macbuild.tool"

    deploy:
      provider: releases
      skip_cleanup: true
      file:
      - Binaries/RELEASE/*.zip
      - Binaries/DEBUG/*.zip
      file_glob: true
      on:
        tags: true
      api_key:
        secure: j+PIYM2H3mtpwdAov4CLg6waz+pJVIpQo/jPgVMp730OAaS2Ypk7OuHlXxvRQDUE79AO6vxNSfhqsR77O/ZxK5xZTSBGTVe2xBJEuaYsYn+pWFOAmFd91hk4kl7Av3XqCSj2BF1eiJW/lAHoY9aZX489re4c4LGaX5tbpK0xAXK3q1Ps0IDLQem6SUK2o6LLYc/tjNAoeRtOXqPY2qW6Xre2iSWCnoTYWZpHr5L3VT/nWq29Xc7MaiDmAO40WK+5hVqqRCPcMYm/N3VmY1SxOznUMjxD472yJUo1QeTX3QhNdSwSbRaIDyRLGQQdV1ZUBIeHMIBaVDbfjm5z2SrORRu7xhrgnDDyManvOGuQkxuoztidr2Bm3RxdkOxkPf4JE/7LIJKkTEUWJks7ieRhe+50WC3AHHnoaKQbaDwlXxyWWl4Uvs2DzRegVq8RXoFfNKuQkFmv8FJuABA+ZQp1ZEaBxVJn5nh/KuUXS1xjgokhtlmgXQgW1M8kafiq/4U1QWILWetAyFPfZmqI0CTBC9bU/1P2klrhCOHpm8jxwncN7pY/IoyjIoZpAGkV1nQlE4QlXKJkrIA24/mgfy+oL+4V7IjIoWtcFQrIWwfVHE/5SEQ1zW2Ur9U2/AoEG5oPf+0ijYLaPAoKLrustwYkDL7L9Me/fZY01yPIjGKrMPw=

  - os: osx
    compiler: clang

    before_install:
      - curl -Ls https://entrust.com/root-certificates/entrust_l1k.cer -o ~/entrust_l1k.crt || exit 1
      - curl -LS https://curl.haxx.se/ca/cacert.pem -o ~/cacert.pem || exit 1
      - cat ~/entrust_l1k.crt >> ~/cacert.pem || exit 1
      - echo "cacert=\"$HOME/cacert.pem\"" > ~/.curlrc || exit 1
      - echo "ca_certificate=$HOME/cacert.pem" > ~/.wgetrc || exit 1

    script:
      - echo "This script runs coverity..."

    addons:
      coverity_scan:
        project:
          name: "acidanthera/AptioFixPkg"
          description: "AptioFixPkg"
        notification_email: $NOTIFICATION_EMAIL
        build_command_prepend: "./macbuild.tool --skip-build --skip-package && cd UDK ; src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/covstrap.sh) && eval \"$src\" || exit 1"
        build_command: "../macbuild.tool --skip-tests --skip-package RELEASE"
        branch_pattern: master
